from . import bot
from . import payments
from . import individual
from . import individual_loan
from . import individual_cards
from . import individual_deposit
from . import individual_money_transfer
from . import legal_entity
from . import legal_entity_internet_banking
from . import legal_entity_loan
from . import legal_entity_other_services
from . import legal_entity_my_bills
from . import feedback
from . import settings
from . import general
from . import exchange_rates
from . import branches
from . import atm
from . import money_transfer
from . import minibank
from . import repayment_of_loans
from . import payment_mobile_operators
from . import individual_mobile
from . import individual_cards_uzcard
from . import individual_cards_humo
from . import individual_cards_visa
from . import individual_cards_unionpay
from . import individual_deposit_national_currency_online
from . import individual_deposit_national_currency_branch
from . import individual_deposit_foreign_currency_branch
from . import individual_deposit_foreign_currency_online
from . import legal_entity_accepting_payment
from . import legal_entity_deposit
from . import individual_tariffs
from . import legal_entity_tariffs